[spawn]
	# Default: 0.05
	# Range: 0.0 ~ 1.0
	chanceToReplaceBossWeapon = 0.05
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	chanceToReplaceNormalWeapon = 0.5
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	dropChanceOverride = 0.1

[weapon_toggles]
	enableAncientSpear = true
	enableCursedBow = true
	enableWrathOfTheDesert = true
	enableWitherAssultShoulderWeapon = true
	enableVoidAssultShoulderWeapon = true
	enableLaserGatling = false
	enableMeatShredder = true
	enableSoulRender = true
	enableGauntletOfMaelstrom = false
	enableInfernalForge = true
	enableVoidForge = true
