[highlight]
	#Highlight color
	color = "#00FF68CF"
	enabled = true
	#Distance at which the player highlight will take effect
	# Default: 20
	# Range: 0 ~ 10000
	distance = 20
	# Default: 100
	# Range: 0 ~ 10000
	duration = 100
